### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by msuntharesan** [google/intermock#1]
Would this ever get publish to npm?

**Comment by dalinarkholin** [comment]
Weird this was opened two hours ago. Also curious.

**Comment by ignacioureta** [comment]
+1

**Comment by ryanmcdermott** [comment]
Thanks for opening this issue! I'm actively working on getting all of the internal requirements to publish this under Google's NPM account. I'll keep you all updated on this issue.

**Comment by Luqih** [comment]
+1

**Comment by ryanmcdermott** [comment]
Sorry for the delay! Haven't gotten the internal resources together yet for this. It's not as simple as `npm publish`

**Comment by ryanmcdermott** [comment]
Here it is everyone :tada: 
https://www.npmjs.com/package/intermock

Let me know if there's any problems!
