### ISSUE TITLE
@mockType can not work well.

### ISSUE THREAD

**Issue by daizch** [google/intermock#15]
I tried to use mockType feature but it won't work well when using `@mockType`. I found out it should be `!mockType` instead after I looked into the code base. The fast way to verify this error is to run the following typescript definition on [https://google.github.io/intermock/](https://google.github.io/intermock/). 

But I also found one existing feature [PR11](https://github.com/google/intermock/pull/11) to support `@mockType`. Maybe because you guys have not republish to npm lol.

the error one

```ts
interface Host {
  /** @mockType {internet.ipv6} */
  addr: string;
}
```

the right one

```ts
interface Host {
  /** !mockType {internet.ipv6} */
  addr: string;
}
```

**Comment by kylebjordahl** [comment]
FWIW - I can confirm from testing today that the jsdoc format (using @) works when building the library from source.

**Comment by ryanmcdermott** [comment]
Sorry I'll update library on NPM as soon as I can.

**Comment by ryanmcdermott** [comment]
Ok it's been updated https://www.npmjs.com/package/intermock

**Comment by daizch** [comment]
@ryanmcdermott thanks man.
