### ISSUE TITLE
No way to select json as output format.

### ISSUE THREAD

**Issue by mbates** [google/intermock#31]
The cli does not allow an outputFormat to be specified, so `formatOutput()` always defaults to the default "object" instead of json.

cli/index.js should have this added to optionDefinitions
`{ name: 'outputFormat', alias: 'o', type: String },`

with that outputFormat added to the options call to `mock()`

**Comment by mbates** [comment]
(I'm putting together a PR to address my 3 issues.)

**Comment by ryanmcdermott** [comment]
Thank you!!

**Comment by mbates** [comment]
resolved with https://github.com/google/intermock/pull/32
